---
abstract: 'easy handling of environment in dotcloud'
author:
  - 'Flavio Poletti <polettix@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300000, CPAN::Meta::Converter version 2.112150'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DotCloud-Environment
requires:
  JSON: 2.53
  YAML: 0.72
  perl: 5.008_000
version: 0.7.0_04
